name = "Model-Gallery"
compatibility_date = "2024-01-01"
main = "worker.js"

# 配置环境变量
[vars]
API_URL = "https://api.openai.com/v1/models"
API_KEY = ""
SITE_ICON = "https://docs.newapi.pro/assets/logo.png"
SITE_NAME = "Model Gallery"
SITE_LOGO = "https://docs.newapi.pro/assets/logo.png"
